gcp_project   = "poc-project-286601"
gcp_region    = "us-central1"
gcp_auth_file = "tf-key.json"
gcp_zone      = "us-central1-c"
//gcp_network = "myvpcnetwork"
//vpn_name      = "terraform-custom-network"
